routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/users', 'UsersController@index');
Route::get('/users/edit/{user_id}', 'UsersController@edit');
Route::post('/user/update/{user_id}', 'UsersController@update')->name('updateUser');
Route::get('/account',  'UsersController@account');
Route::post('/account/update/{user_id}', 'UsersController@accountUpdate')->name('updateAccount');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', 'TransactionsController@index');
Route::get('/accountsReceivable', 'AccountsReceivableController@index');
Route::get('/transaction', 'TransactionController@index');
Route::get('/transaction/index', 'TransactionController@index');
Route::post('/transaction/import', 'TransactionController@import');
Route::get('/transaction/transaction/{id}', 'TransactionController@single');
Route::get('/transaction/transaction/{id}/{type}', 'TransactionController@single');
Route::get('/transaction/getVehiclesByCustomer/{id}', 'TransactionController@getVehiclesByCustomer');
Route::get('/transaction/update/{id}/done/{type}', 'TransactionController@markAsDone');
Route::get('/transaction/update/{id}/asf/{type}', 'TransactionController@markAsAsf');
Route::get('/transaction/create/walkin', 'TransactionsController@createWalkin');
Route::get('/transaction/create/corporate', 'TransactionsController@createCorporate');
Route::get('/transaction/create/quote', 'TransactionsController@createQuote');

Route::get('/transaction/markAsDone/{id}', 'TransactionController@pendingItemMarkAsDone');
Route::get('/transaction/markAsAsf/{id}', 'TransactionController@doneItemMarkAsAsf');

Route::get('/transaction/printTransaction/{id}', 'TransactionController@printTransaction');
Route::get('/transaction/printAfter/{id}', 'TransactionController@printAfter');

Route::get('/quotes/approve/{id}', 'QuotesController@approveQuote');
Route::get('/quotes/disapprove/{id}', 'QuotesController@disapproveQuote');

Route::get('/reports', 'ReportsController@index');
Route::get('/notifications', 'ReportsController@notifications');
Route::get('/notifications/{type}/{status}', 'ReportsController@notifications');
Route::get('/reports/notifications', 'ReportsController@reports_notifications');
Route::get('/reports/notifications/{type}', 'ReportsController@reports_notifications_redirect');
Route::get('/transaction/transaction/', 'ReportsController@index');
Route::get('/notifications/{type1}/{type2}', 'ReportsController@notifications_redirect');
Route::get('/reports/filter/', 'ReportsController@show_with_filter');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');
Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

Route::get('/notifications/refresh-notification', 'ReportsController@refreshNotification');
Route::post('/refresh-notification-record', 'ReportsController@updateNotificationRecord');

Route::get('/product-orders', 'ProductsController@productOrderIndex');
Route::get('/product-orders/paid', 'ProductsController@productOrderIndexPaid');
Route::get('/product-orders/incomplete', 'ProductsController@productOrderIndexIncomplete');
Route::get('/product-orders/add', 'ProductsController@productOrderAdd');
Route::post('/product-orders/insert', 'ProductsController@productOrderInsert');
Route::get('/product-orders/order/{id}', 'ProductsController@productOrderShow');
Route::get('/product-orders/edit/order/{id}', 'ProductsController@productOrderEdit');
Route::post('/product-orders/update/order/{id}', 'ProductsController@productOrderUpdate');
Route::delete('/product-orders/delete/order/{id}', 'ProductsController@productOrderDelete');
Route::get('/product-orders/add-delivery/{id}', 'ProductsController@productOrderDeliveryAdd');
Route::post('/product-orders/add-delivery/{id}/insert', 'ProductsController@productOrderDeliveryInsert');
Route::get('/product-orders/edit-delivery/{id}', 'ProductsController@productOrderDeliveryEdit');
Route::post('/product-orders/edit-delivery/{id}/update', 'ProductsController@productOrderDeliveryUpdate');
Route::get('/product-orders/add-payment/{id}', 'ProductsController@productOrderPaymentAdd');
Route::post('/product-orders/add-payment/{id}/insert', 'ProductsController@productOrderPaymentInsert');
Route::get('/product-orders/edit-payment/{id}', 'ProductsController@productOrderPaymentEdit');
Route::post('/product-orders/edit-payment/{id}/update', 'ProductsController@productOrderPaymentUpdate');

Route::resource('customerVehicles', 'CustomerVehiclesController');
Route::get('/customerVehicles/create/{id}', 'CustomerVehiclesController@create');

Route::get('payment/createFromTransaction/{id}', 'PaymentController@createFromTransaction');

Route::get('/transactions/delete/{id}', 'TransactionsController@delete');
Route::delete('/transactions/delete/{id}', 'TransactionsController@delete');
Route::get('/customers/delete/{id}', 'CustomersController@destroy');
Route::get('/products/delete/{id}', 'ProductsController@destroy');


Route::post('/customers/ajax/add', 'CustomersController@ajaxadd');
Route::get('/customers/gettransactiondetails/{transid}', 'CustomersController@showAjax');
Route::post('/personnel/ajax/add', 'PersonnelController@ajaxadd');
Route::post('/product/ajax/add', 'ProductsController@ajaxadd');


Route::resource('customers', 'CustomersController');
Route::resource('products', 'ProductsController');
Route::resource('brands', 'BrandsController');
Route::resource('types', 'TypesController');
Route::resource('walkins', 'WalkinsController');
Route::resource('corporates', 'CorporatesController');
Route::resource('transactions', 'TransactionsController');
Route::resource('afterSales', 'AfterSalesController');
Route::resource('priceHistories', 'PriceHistoryController');
Route::resource('qtyHistories', 'QtyHistoryController');
Route::resource('accountsReceivable', 'AccountsReceivableController');
Route::resource('asfTransactions', 'AsfTransactionsController');
Route::resource('personnels', 'PersonnelController');
Route::resource('services', 'ServicesController');
Route::resource('suppliers', 'SupplierController');
Route::resource('customerVehicles', 'CustomerVehiclesController');
Route::resource('quotes', 'QuotesController');
Route::resource('payments', 'PaymentController');
Route::resource('roles', 'RolesController');
Route::resource('user', 'UserController');
Route::resource('accountsPayable', 'AccountsPayableController');

Route::get('/getBaseURL', 'HomeController@getBaseURL');

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTransactionsRequest;
use App\Http\Requests\UpdateTransactionsRequest;
use App\Repositories\TransactionsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;



use App\Models\Services; // JP 1
use App\Models\Customers; // JP 2
use App\Models\Products; // JP 2
use App\Models\Payment;
use App\Transaction; // JP 1



class TransactionsController extends AppBaseController
{
    /** @var  TransactionsRepository */
    private $transactionsRepository;

    public function __construct(TransactionsRepository $transactionsRepo)
    {
        $this->transactionsRepository = $transactionsRepo;
        $this->middleware('auth');
    }

    /**
     * Display a listing of the Transactions.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $transactions = DB::table('transactions as t')
            ->select('t.id', 't.date', 't.odo_reading', 't.subtotal', 't.km_run', 't.is_done', 't.created_at', 't.charge_invoice', 'c.name as customer_name', 'c.contact as customer_contact', 'c.is_company',
                'v.make as vehicle_name', 'p.name as product_name', 'd.plate as detail_plate',
                'd.color as detail_color', 'p.name as personnel_name')
            ->leftJoin('customers as c', 'c.id', '=', 't.customer_id')
            ->leftJoin('customer_vehicles as cv', 'cv.detail_id', '=', 't.detail_id')
            ->leftJoin('vehicles as v', 'v.id', '=', 'cv.vehicle_id')
            ->leftJoin('details as d', 'd.id', '=', 't.detail_id')
            ->leftJoin('personnels as p', 'p.id', '=', 't.personnel_id')
            ->where('t.is_quote', 0)
            ->orderBy('t.date')
            ->get();

        return view('transactions.index')
            ->with('transactions', $transactions);
    }

    /**
     * Show the form for creating a new Transactions.
     *
     * @return Response
     */
    public function create()
    {
                                              // JP 
        $customers = $this->getAllCustomers();
        $products = $this->getAllProducts();
        $serviceProducts = $this->getAllProductsByServiceId();
        $productsObject = $this->getAllProducts(true);
        $personnels = $this->getAllPersonnel();

        $vehicles = array('0' => '---');


        $services = Services::select("id", "name")->get();
        $serviceProds = $this->createProductServicesJson();


        return view('transactions.create')
            ->with('customers', $customers)
            ->with('products', $products)
            ->with('serviceProducts', $serviceProducts)
            ->with('personnels', $personnels)
            ->with('productsObject', $productsObject)
            ->with('services', $services)
            ->with('vehicles', $vehicles)
            ->with('serviceProds', $serviceProds)
            ->with('type', '');
    }

    /**
     * Store a newly created Transactions in storage.
     *
     * @param CreateTransactionsRequest $request
     *
     * @return Response
     */
    public function store(CreateTransactionsRequest $request)
    {
        $input = $request->all();
        
        // date
        $dateClass = Carbon::now();
        $today = $dateClass->toDateTimeString();

        // get detail id and vehicle id
        $detailId = $input['detail_id'];
        $vehicleIdClass = DB::table('details')->where('id', $detailId )->select('vehicle_id')->first(); //JP CHange
        $vehicleId = !is_null($vehicleIdClass) ? $vehicleIdClass->vehicle_id : 0; // JP Change
        
        // convert kmrun to int
        $kmRunInt = preg_replace("/[^0100-9]/","", $input['km_run']);
        $kmRunInt = intval($kmRunInt); // JP Change

        $odoReading = isset($input['odo_reading']) ? $input['odo_reading'] : 0;

        if (isset($input['is_quote'])) {
            $modelyear = $input['modelyear'];
            $transactionId = DB::table('transactions')->insertGetId([
                'date'              => $input['date'],
                'customer_id'       => $input['customer_id'],
                'vehicle_id'        => $vehicleId,
                'product_id'        => 0,
                'detail_id'         => $detailId,
                'modelyear'         => $modelyear,
                'subtotal'          => $input['subtotal'] ? $input['subtotal'] : 0,
                'discount'          => $input['discount'] ? $input['discount'] : 0,
                'total'             => $input['total'] ? $input['total'] : 0,
                'rendered'          => $input['rendered'] ? $input['rendered'] : 0,
                'balance'           => $input['balance'] ? $input['balance'] : 0,
                'km_run'            => $kmRunInt,
                'is_quote'          => $input['is_quote'] ? $input['is_quote'] : 0,
                'personnel_id'      => $input['personnel_id'],
                'charge_invoice'    => isset($input['charge_invoice']) ? $input['charge_invoice'] : '',
                'created_at'        => $today,
                'updated_at'        => $today
            ]);
        }else{
            // save transactions first
            $transactionId = DB::table('transactions')->insertGetId([
                'date'              => $input['date'],
                'customer_id'       => $input['customer_id'],
                'vehicle_id'        => $vehicleId,
                'product_id'        => 0,
                'detail_id'         => $detailId,
                'odo_reading'       => $odoReading,
                'subtotal'          => $input['subtotal'] ? $input['subtotal'] : 0,
                'discount'          => $input['discount'] ? $input['discount'] : 0,
                'total'             => $input['total'] ? $input['total'] : 0,
                'rendered'          => $input['rendered'] ? $input['rendered'] : 0,
                'balance'           => $input['balance'] ? $input['balance'] : 0,
                'km_run'            => $kmRunInt,
                'is_quote'          => $input['is_quote'] ? $input['is_quote'] : 0,
                'personnel_id'      => $input['personnel_id'],
                'charge_invoice'    => isset($input['charge_invoice']) ? $input['charge_invoice'] : '',
                'created_at'        => $today,
                'updated_at'        => $today
            ]);
        }
        

        // save products next
        $product_ids = $input["product_ids"];
        $qtys = $input["qtys"];
        $prices = $input["prices"];
        $subtotals = $input["subtotals"];
        $notes = $input["notes"];

        $lastProductId = 0;
        for($i = 0; $i < count($product_ids); $i++)
        {
            if ($product_ids[$i] > 0)
            {
                $productQty = $qtys[$i] ? $qtys[$i] : 0;
                $productId = $product_ids[$i];
                $lastProductId = $product_ids[$i];
                DB::table('transaction_products')->insertGetId([
                    'transaction_id'    => $transactionId,
                    'product_id'        => $productId,
                    'odo_reading'       => $odoReading,
                    'qty'               => $productQty,
                    'unit'              => 'pc',
                    'price'             => $prices[$i] ? $prices[$i] : 0,
                    'subtotal'          => $subtotals[$i] ? $subtotals[$i] : 0,
                    'notes'             => $notes[$i] ? $notes[$i] : '',
                    'created_at'        => $today,
                    'updated_at'        => $today
                ]);

                // deduct product qty
                $currentProductQty = DB::table('products')->where('id', $productId)->value('qty');
                $adjusted = $currentProductQty - $productQty;

                DB::table('qty_history')->insertGetId([
                    'product_id'    => $productId,
                    'qty'           => $adjusted,
                    'adjusted'      => $productQty,
                    'note'          => $productQty . " Items Bought",
                    'created_at'    => $today,
                    'updated_at'    => $today
                ]);

                DB::table('products')->where('id', $productId)->decrement('qty', $productQty);

            }
        }

        // save services next
        $service_ids = $input["service_ids"];
        $service_product_ids = $input["service_product_ids"];
        $service_details = $input["service_details"];
        $service_qtys = $input["service_qtys"];
        $service_units = $input["service_units"];
        $service_subtotals = $input["service_subtotals"];

        for ($i = 0; $i < count($service_ids); $i++)
        {
            if ($service_ids[$i] > 0)
            {
                DB::table('transaction_services')->insertGetId([
                    'transaction_id'    => $transactionId,
                    'service_id'        => $service_ids[$i],
                    'details'           => $service_details[$i] ? $service_details[$i] : '',
                    'product_id'        => $service_product_ids[$i],
                    'qty'               => $service_qtys[$i],
                    'unit'              => $service_units[$i],
                    'subtotal'          => $service_subtotals[$i] ? $service_subtotals[$i] : 0
                ]);
            }
        }

        // update transaction
        DB::table('transactions')
            ->where('id', $transactionId)
            ->update(['product_id' => $lastProductId, 'odo_reading' => $odoReading]);


        //STORE TO PAYMENT IF PAYMENT HAS BEEN MADE - NEW WALKIN
        if (is_null($input["is_quote"])) {
            if (intval($input['rendered']) > 0) {
                
                DB::table('payment_history')->insertGetId([

resources/views/transactions/create.blade.php
@extends('layouts.admin')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <section class="content-header">
                <h1 class="page-header"><span class="fa fa-plus-circle"></span> Add Transaction {{ $type }}</h1>
            </section>

            @include('adminlte-templates::common.errors')
            {!! Form::open(['route' => 'transactions.store', 'class' => 'form-horizontal']) !!}


            <div class="panel panel-default">
                <div class="panel-heading">Customer Information</div>
                <div class="panel-body">
                    @include('transactions.fields')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Product Information</div>
                <div class="panel-body">
                    @include('transactions.products')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Labor Information</div>
                <div class="panel-body">
                    @include('transactions.services')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Payment Information</div>
                <div class="panel-body">
                    @include('transactions.payment')
                </div>
            </div>

            <!-- Submit Field -->
            <div class="form-group">
                <div class="col-md-6 col-md-offset-1">
                    <a href="{!! route('transactions.index') !!}" class="btn btn-default">Cancel</a>
                    {!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
                </div>
            </div>

            {!! Form::close() !!}

        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function(event) { 
            function checkProductSelectAndRemovePast(tryThisValue, removeThisValue){
                let theOptions = $("body .transaction-services #serviceProdsSelect");

                if (theOptions.find("option").length > 0) {
                    theOptions.find("option[value="+removeThisValue+"]").remove();
                }

                theOptions.find("option").each(function(index, el) {
                    if ($(el).val() == tryThisValue) {
                        return false;
                    }
                });
                return true;
            }
    
            $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                let selected = $("body .transaction-services #serviceProdsSelect option:first").val();
                if (selected != null) {
                    let product = data.filter(v => v.id == selected);    
                    $(".transaction-services #serviceTypeInput").val(product[0].servicename);
                    $(".transaction-products .initial-product input.price-field").val(product[0].price);
                }
            });

            // Every change of product
            $("#serviceProdsSelect").on('change', function(e) {
                e.preventDefault();
                let theElement = $(this);

                $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                    let selected = theElement.find("option:selected").val();
                    let productname = data.filter(function(e){return e.id == selected});
                    theElement.parent().parent().find("input[id='serviceTypeInput']").val(productname[0].servicename);
                    theElement.parent().parent().find("input[id='serviceTypeInputHidden']").val(productname[0].service_id);
                });
            });

            var theSelectOrig;
            $("body .transaction-products").on('focus', 'select:not(:disabled).selectformcontrol', function(event) {
                theSelectOrig = $(this);
                theSelectOrig.data('previous', theSelectOrig.val());
            }).on('change', 'select:not(:disabled).selectformcontrol', function() {
                let theSelectedProductVal = theSelectOrig.find("option:selected").val();
                let theSelectedProductText = theSelectOrig.find("option:selected").text();
                /*console.log(theSelectOrig.parent().parent().find("input.price-field"));*/

                $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                    if (theSelectedProductVal != null) {
                        let product = data.filter(v => v.id == theSelectedProductVal);    
                        theSelectOrig.parent().parent().find("input.price-field").val(product[0].price).trigger('keyup');
                    }
                });

                if (checkProductSelectAndRemovePast(theSelectedProductVal, theSelectOrig.data("previous"))){
                    $("body .transaction-services #serviceProdsSelect").append(new Option(theSelectedProductText, theSelectedProductVal));    
                    $("body .transaction-services #serviceProdsSelect").trigger('change');
                }
                theSelectOrig.data('previous', theSelectedProductVal);
            });
        });

    </script>
@endsection

resources/views/transactions/create_quote.blade.php
@extends('layouts.admin')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <section class="content-header">
                <h1 class="page-header"><span class="fa fa-plus-circle"></span> Temporary Service Record</h1>
            </section>

            @include('adminlte-templates::common.errors')
            {!! Form::open(['route' => 'transactions.store', 'class' => 'form-horizontal']) !!}


            <div class="panel panel-default">
                <div class="panel-heading">Customer Information</div>
                <div class="panel-body">
                    @include('transactions.fields_quote')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Product Information</div>
                <div class="panel-body">
                    @include('transactions.products')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Labor Information</div>
                <div class="panel-body">
                    @include('transactions.services')
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading">Payment Information</div>
                <div class="panel-body">
                    @include('transactions.payment')
                </div>
            </div>

            <!-- Submit Field -->
            <div class="form-group">
                <div class="col-md-6 col-md-offset-1">
                    <a href="{!! route('transactions.index') !!}" class="btn btn-default">Cancel</a>
                    {!! Form::submit('Save', ['class' => 'btn btn-default']) !!}
                </div>
            </div>

            {!! Form::close() !!}

        </div>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function(event) { 
            function checkProductSelectAndRemovePast(tryThisValue, removeThisValue){
                let theOptions = $("body .transaction-services #serviceProdsSelect");

                if (theOptions.find("option").length > 0) {
                    theOptions.find("option[value="+removeThisValue+"]").remove();
                }

                theOptions.find("option").each(function(index, el) {
                    if ($(el).val() == tryThisValue) {
                        return false;
                    }
                });
                return true;
            }
    
            $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                let selected = $("body .transaction-services #serviceProdsSelect option:first").val();
                if (selected != null) {
                    let product = data.filter(v => v.id == selected);    
                    $(".transaction-services #serviceTypeInput").val(product[0].servicename);
                    $(".transaction-products .initial-product input.price-field").val(product[0].price);
                }
            });

            // Every change of product
            $("#serviceProdsSelect").on('change', function(e) {
                e.preventDefault();
                let theElement = $(this);

                $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                    let selected = theElement.find("option:selected").val();
                    let productname = data.filter(function(e){return e.id == selected});
                    theElement.parent().parent().find("input[id='serviceTypeInput']").val(productname[0].servicename);
                    theElement.parent().parent().find("input[id='serviceTypeInputHidden']").val(productname[0].service_id);
                });
            });

            var theSelectOrig;
            $("body .transaction-products").on('focus', 'select:not(:disabled).selectformcontrol', function(event) {
                theSelectOrig = $(this);
                theSelectOrig.data('previous', theSelectOrig.val());
            }).on('change', 'select:not(:disabled).selectformcontrol', function() {
                let theSelectedProductVal = theSelectOrig.find("option:selected").val();
                let theSelectedProductText = theSelectOrig.find("option:selected").text();
                /*console.log(theSelectOrig.parent().parent().find("input.price-field"));*/

                $.getJSON("{{url("/json/serviceProds.json")}}", function(data){
                    if (theSelectedProductVal != null) {
                        let product = data.filter(v => v.id == theSelectedProductVal);    
                        theSelectOrig.parent().parent().find("input.price-field").val(product[0].price).trigger('keyup');
                    }
                });

                if (checkProductSelectAndRemovePast(theSelectedProductVal, theSelectOrig.data("previous"))){
                    $("body .transaction-services #serviceProdsSelect").append(new Option(theSelectedProductText, theSelectedProductVal));    
                    $("body .transaction-services #serviceProdsSelect").trigger('change');
                }
                theSelectOrig.data('previous', theSelectedProductVal);
            });
        });

    </script>
@endsection

resources/views/transactions/index.blade.php
@extends('layouts.admin')
@section('content')
    <div id="page-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        <span class="fa fa-list"></span> Transactions
                    </h1>
                </div>
            </div>
            {{--<a href="{!! route('transactions.create') !!}" class="cta-link"><span class="fa fa-plus-circle"></span> Create New Transaction</a>--}}
            <div class="cta-link">
                <a href="{{ url('/transaction/create/walkin') }}"><span class="fa fa-plus-circle"></span> Create New - Walk-in</a> &nbsp; | &nbsp;
                <a href="{!! url('/transaction/create/corporate') !!}"><span class="fa fa-plus-circle"></span> Create New - Corporate</a> &nbsp; | &nbsp;
                <a href="{!! url('/transaction/create/quote') !!}"><span class="fa fa-plus-circle"></span> Create Quotation</a>
            </div>
            <div class="content">
                <div class="clearfix"></div>

                @include('flash::message')

                @if(Input::get('ok') == '1')
                    <div class="alert alert-success">
                        Transactions saved successfully.
                    </div>
                @endif

                <div class="clearfix"></div>
                <div class="box box-primary">
                    <div class="box-body">
                        @include('transactions.table')
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/transactions/table.blade.php
<table class="table table-hover table-striped transactions-table" id="transactions-table">
    <thead>
        <tr>
            <th>Date</th>
            <th>Customer</th>
            <th>Charge Invoice</th>
            <th>Vehicle</th>
            <th>Personnel</th>
            <th>Detail</th>
            <th>Odo Reading</th>
            <th>Subtotal</th>
            <th>Km Run</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach($transactions as $transactions)
        <tr>
            <td>{{ Carbon\Carbon::parse($transactions->date)->format('Y/m/d') }}</td>
            <td><a href="<?=url('/')?>/transaction/transaction/{{ $transactions->id }}">{!! $transactions->customer_name !!}</a></td>
            <td>{{ $transactions->charge_invoice or "" }}</td>
            <td>{!! $transactions->vehicle_name !!}</td>
            <td>{!! $transactions->personnel_name !!}</td>
            <td>{!! $transactions->detail_plate !!} ({!! $transactions->detail_color !!})</td>
            <td>{!! $transactions->odo_reading !!}</td>
            <td>{!! $transactions->subtotal !!}</td>
            <td>{!! $transactions->km_run !!}</td>
            <td class="table-cta-data">
                <a href="{!! route('transactions.edit', [$transactions->id]) !!}" class="table-edit-cta" title="Edit Transaction"><i class="glyphicon glyphicon-edit"></i></a> |
                <a href="<?=url('/')?>/transaction/printTransaction/{{ $transactions->id }}" class="table-edit-cta" title="Print Transaction" target="_blank"><i class="fa fa-print"></i></a>
                |
                {!! Form::open(['action' => array('TransactionsController@delete', $transactions->id), 'method' => 'delete', 'style' => 'display: inline-block;']) !!}
                    {!! Form::button('<span class="glyphicon glyphicon-trash "></span>', ['type' => 'submit', 'class' => 'btn btn-danger table-delete-cta', 'onclick' => "return confirm('Are you sure?')"]) !!}
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>