routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/users', 'UsersController@index');
Route::get('/users/edit/{user_id}', 'UsersController@edit');
Route::post('/user/update/{user_id}', 'UsersController@update')->name('updateUser');
Route::get('/account',  'UsersController@account');
Route::post('/account/update/{user_id}', 'UsersController@accountUpdate')->name('updateAccount');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

Route::get('/', 'TransactionsController@index');
Route::get('/accountsReceivable', 'AccountsReceivableController@index');
Route::get('/transaction', 'TransactionController@index');
Route::get('/transaction/index', 'TransactionController@index');
Route::post('/transaction/import', 'TransactionController@import');
Route::get('/transaction/transaction/{id}', 'TransactionController@single');
Route::get('/transaction/transaction/{id}/{type}', 'TransactionController@single');
Route::get('/transaction/getVehiclesByCustomer/{id}', 'TransactionController@getVehiclesByCustomer');
Route::get('/transaction/update/{id}/done/{type}', 'TransactionController@markAsDone');
Route::get('/transaction/update/{id}/asf/{type}', 'TransactionController@markAsAsf');
Route::get('/transaction/create/walkin', 'TransactionsController@createWalkin');
Route::get('/transaction/create/corporate', 'TransactionsController@createCorporate');
Route::get('/transaction/create/quote', 'TransactionsController@createQuote');

Route::get('/transaction/markAsDone/{id}', 'TransactionController@pendingItemMarkAsDone');
Route::get('/transaction/markAsAsf/{id}', 'TransactionController@doneItemMarkAsAsf');

Route::get('/transaction/printTransaction/{id}', 'TransactionController@printTransaction');
Route::get('/transaction/printAfter/{id}', 'TransactionController@printAfter');

Route::get('/quotes/approve/{id}', 'QuotesController@approveQuote');
Route::get('/quotes/disapprove/{id}', 'QuotesController@disapproveQuote');

Route::get('/reports', 'ReportsController@index');
Route::get('/notifications', 'ReportsController@notifications');
Route::get('/notifications/{type}/{status}', 'ReportsController@notifications');
Route::get('/reports/notifications', 'ReportsController@reports_notifications');
Route::get('/reports/notifications/{type}', 'ReportsController@reports_notifications_redirect');
Route::get('/transaction/transaction/', 'ReportsController@index');
Route::get('/notifications/{type1}/{type2}', 'ReportsController@notifications_redirect');
Route::get('/reports/filter/', 'ReportsController@show_with_filter');

Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');
Route::get('field_template', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@fieldTemplate');
Route::post('generator_builder/generate', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@generate');

Route::get('/notifications/refresh-notification', 'ReportsController@refreshNotification');
Route::post('/refresh-notification-record', 'ReportsController@updateNotificationRecord');

Route::get('/product-orders', 'ProductsController@productOrderIndex');
Route::get('/product-orders/paid', 'ProductsController@productOrderIndexPaid');
Route::get('/product-orders/incomplete', 'ProductsController@productOrderIndexIncomplete');
Route::get('/product-orders/add', 'ProductsController@productOrderAdd');
Route::post('/product-orders/insert', 'ProductsController@productOrderInsert');
Route::get('/product-orders/order/{id}', 'ProductsController@productOrderShow');
Route::get('/product-orders/edit/order/{id}', 'ProductsController@productOrderEdit');
Route::post('/product-orders/update/order/{id}', 'ProductsController@productOrderUpdate');
Route::delete('/product-orders/delete/order/{id}', 'ProductsController@productOrderDelete');
Route::get('/product-orders/add-delivery/{id}', 'ProductsController@productOrderDeliveryAdd');
Route::post('/product-orders/add-delivery/{id}/insert', 'ProductsController@productOrderDeliveryInsert');
Route::get('/product-orders/edit-delivery/{id}', 'ProductsController@productOrderDeliveryEdit');
Route::post('/product-orders/edit-delivery/{id}/update', 'ProductsController@productOrderDeliveryUpdate');
Route::get('/product-orders/add-payment/{id}', 'ProductsController@productOrderPaymentAdd');
Route::post('/product-orders/add-payment/{id}/insert', 'ProductsController@productOrderPaymentInsert');
Route::get('/product-orders/edit-payment/{id}', 'ProductsController@productOrderPaymentEdit');
Route::post('/product-orders/edit-payment/{id}/update', 'ProductsController@productOrderPaymentUpdate');

Route::resource('customerVehicles', 'CustomerVehiclesController');
Route::get('/customerVehicles/create/{id}', 'CustomerVehiclesController@create');

Route::get('payment/createFromTransaction/{id}', 'PaymentController@createFromTransaction');

Route::get('/transactions/delete/{id}', 'TransactionsController@delete');
Route::delete('/transactions/delete/{id}', 'TransactionsController@delete');
Route::get('/customers/delete/{id}', 'CustomersController@destroy');
Route::get('/products/delete/{id}', 'ProductsController@destroy');


Route::post('/customers/ajax/add', 'CustomersController@ajaxadd');
Route::get('/customers/gettransactiondetails/{transid}', 'CustomersController@showAjax');
Route::post('/personnel/ajax/add', 'PersonnelController@ajaxadd');
Route::post('/product/ajax/add', 'ProductsController@ajaxadd');


Route::resource('customers', 'CustomersController');
Route::resource('products', 'ProductsController');
Route::resource('brands', 'BrandsController');
Route::resource('types', 'TypesController');
Route::resource('walkins', 'WalkinsController');
Route::resource('corporates', 'CorporatesController');
Route::resource('transactions', 'TransactionsController');
Route::resource('afterSales', 'AfterSalesController');
Route::resource('priceHistories', 'PriceHistoryController');
Route::resource('qtyHistories', 'QtyHistoryController');
Route::resource('accountsReceivable', 'AccountsReceivableController');
Route::resource('asfTransactions', 'AsfTransactionsController');
Route::resource('personnels', 'PersonnelController');
Route::resource('services', 'ServicesController');
Route::resource('suppliers', 'SupplierController');
Route::resource('customerVehicles', 'CustomerVehiclesController');
Route::resource('quotes', 'QuotesController');
Route::resource('payments', 'PaymentController');
Route::resource('roles', 'RolesController');
Route::resource('user', 'UserController');
Route::resource('accountsPayable', 'AccountsPayableController');

Route::get('/getBaseURL', 'HomeController@getBaseURL');

app/Models/CustomerVehicles.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class CustomerVehicles
 * @package App\Models
 * @version May 22, 2017, 1:50 pm UTC
 */
class CustomerVehicles extends Model
{
    use SoftDeletes;

    public $table = 'customer_vehicles';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'customer_id',
        'vehicle_id',
        'detail_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'customer_id' => 'integer',
        'vehicle_id' => 'integer',
        'detail_id' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    
}

app/Http/Controllers/CustomerVehiclesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateCustomerVehiclesRequest;
use App\Http\Requests\UpdateCustomerVehiclesRequest;
use App\Repositories\CustomerVehiclesRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;
use Illuminate\Support\Facades\DB;

class CustomerVehiclesController extends AppBaseController
{
    /** @var  CustomerVehiclesRepository */
    private $customerVehiclesRepository;

    public function __construct(CustomerVehiclesRepository $customerVehiclesRepo)
    {
        $this->customerVehiclesRepository = $customerVehiclesRepo;
    }

    /**
     * Display a listing of the CustomerVehicles.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->customerVehiclesRepository->pushCriteria(new RequestCriteria($request));
        $customerVehicles = $this->customerVehiclesRepository->all();

        return view('customer_vehicles.index')
            ->with('customerVehicles', $customerVehicles);
    }

    /**
     * Show the form for creating a new CustomerVehicles.
     *
     * @return Response
     */
    public function create($id)
    {
        return view('customer_vehicles.create')->with('customer_id', $id);
    }

    /**
     * Store a newly created CustomerVehicles in storage.
     *
     * @param CreateCustomerVehiclesRequest $request
     *
     * @return Response
     */
    public function store(CreateCustomerVehiclesRequest $request)
    {

        $input = $request->all();

        $backUrl = $input['customer_url'];
        $make = $input['make'];
        $plate = $input['plate'];
        $color = $input['color'];
        $customerId = $input['customer_id'];

        // update vehicle
        $vehicleId = DB::table('vehicles')->insertGetId(['make' => $make]);
        $detailId = DB::table('details')->insertGetId(['plate' => $plate, 'color' => $color, 'vehicle_id' => $vehicleId]);

        $customerId = DB::table('customer_vehicles')->insertGetId([
            'customer_id'   => $customerId,
            'vehicle_id'    => $vehicleId,
            'detail_id'     => $detailId
        ]);

        Flash::success('Customer vehicle updated successfully.');

        return redirect($backUrl);
    }

    /**
     * Display the specified CustomerVehicles.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $customerVehicles = $this->customerVehiclesRepository->findWithoutFail($id);

        if (empty($customerVehicles)) {
            Flash::error('Customer Vehicles not found');

            return redirect(route('customers.index'));
        }

        return view('customer_vehicles.show')->with('customerVehicles', $customerVehicles);
    }

    /**
     * Show the form for editing the specified CustomerVehicles.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
//        $customerVehicles = $this->customerVehiclesRepository->findWithoutFail($id);

        $customerVehicles = DB::table('customer_vehicles as cv')
            ->select('cv.id as id', 'cv.vehicle_id as vehicle_id', 'cv.customer_id as customer_id', 'cv.detail_id as detail_id', 'v.make as make', 'd.plate as plate', 'd.color as color')
            ->leftJoin('vehicles as v', 'v.id', '=', 'cv.vehicle_id')
            ->leftJoin('details as d', 'd.id', '=', 'cv.detail_id')
            ->where('cv.id', '=', $id)->first();

//        $customerVehicles = DB::table('customer_vehicles')->where("id", "=", $id)->first();

        if (empty($customerVehicles)) {
            Flash::error('Customer Vehicles not found');

            return redirect(route('customers.index'));
        }



        return view('customer_vehicles.edit')->with('customerVehicles', $customerVehicles);
    }

    /**
     * Update the specified CustomerVehicles in storage.
     *
     * @param  int              $id
     * @param UpdateCustomerVehiclesRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateCustomerVehiclesRequest $request)
    {
        $input = $request->all();
        $backUrl = $input['customer_url'];
        $vehicleId = $input["vehicle_id"];
        $make = $input['make'];
        $detailId = $input['detail_id'];
        $plate = $input['plate'];
        $color = $input['color'];

        // update vehicle
        $update_vehicleId = 0;
        if ($vehicleId > 0)
        {
            DB::table('vehicles')->where('id', $vehicleId)->update(['make' => $make]);
            $update_vehicleId = $vehicleId;
        }
        else
        {
            $vehicleId = DB::table('vehicles')->insertGetId(['make' => $make]);
            $update_vehicleId = $vehicleId;
        }

        $update_detailId = 0;
        if ($detailId > 0)
        {
            DB::table('details')->where('id', $detailId)->update(['plate' => $plate, 'color' => $color]);
            $update_detailId = $detailId;
        }
        else
        {
            $detailId = DB::table('details')->insertGetId(['plate' => $plate, 'color' => $color]);
            $update_detailId = $detailId;
        }

        DB::table('customer_vehicles')->where('id', $id)->update(['vehicle_id' => $update_vehicleId, 'detail_id' => $update_detailId]);

        Flash::success('Customer vehicle updated successfully.');

        return redirect($backUrl);
    }

    /**
     * Remove the specified CustomerVehicles from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $customerVehicles = DB::table("customer_vehicles")->where("id", "=", $id)->first();

        if (empty($customerVehicles)) {
            Flash::error('Customer Vehicles not found');

            return redirect(route('customers.index'));
        }

        // $this->customersRepository->delete($id);
        DB::table('customer_vehicles')->where("id", "=", $id)->delete();

        Flash::success('Customer Vehicles deleted successfully.');

        return redirect(route('customers.show', [$customerVehicles->customer_id]));
    }
}

resources/views/customer_vehicles/create.blade.php
@extends('layouts.admin')
@section('content')

<div id="page-wrapper">
    <div class="container-fluid">
        <section class="content-header">
            <h1 class="page-header"><span class="fa fa-plus-circle"></span> Add Customer Vehicle</h1>
        </section>
        <div class="panel panel-default">
            <div class="panel-heading">Fill in customer information</div>
            <div class="panel-body">
                @include('adminlte-templates::common.errors')
                {!! Form::open(['route' => 'customerVehicles.store']) !!}

                @include('customer_vehicles.fields')

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/customer_vehicles/edit.blade.php
@extends('layouts.admin')
@section('content')

    <div id="page-wrapper">
        <div class="container-fluid">
            <section class="content-header">
                <h1 class="page-header"><span class="fa fa-pencil-square-o"></span> Edit Customer Vehicle</h1>
            </section>
            <div class="panel panel-default">
                <div class="panel-body">
                    {!! Form::model($customerVehicles, ['route' => ['customerVehicles.update', $customerVehicles->id], 'method' => 'patch']) !!}

                    @include('customer_vehicles.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer_vehicles/fields.blade.php
<!-- Customer Id Field -->

<div class="form-group col-sm-6">
    {!! Form::label('make', 'Make:') !!}
    {!! Form::text('make', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('plate', 'Plate Number:') !!}
    {!! Form::text('plate', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('color', 'Color:') !!}
    {!! Form::text('color', null, ['class' => 'form-control']) !!}
</div>

@if(isset($customer_id))
    <div class="form-group col-sm-6 hidden">
        {!! Form::label('customer_id', 'Customer Id:') !!}
        {!! Form::number('customer_id', $customer_id, ['class' => 'form-control']) !!}
    </div>
@else
    <div class="form-group col-sm-6 hidden">
        {!! Form::label('customer_id', 'Customer Id:') !!}
        {!! Form::number('customer_id', null, ['class' => 'form-control']) !!}
    </div>
@endif

<!-- Vehicle Id Field -->
<div class="form-group col-sm-6 hidden">
    {!! Form::label('vehicle_id', 'Vehicle Id:') !!}
    {!! Form::number('vehicle_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Detail Id Field -->
<div class="form-group col-sm-6 hidden">
    {!! Form::label('detail_id', 'Detail Id:') !!}
    {!! Form::number('detail_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::hidden('customer_url', URL::previous()) !!}
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! URL::previous() !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/customer_vehicles/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Customer Vehicles</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('customerVehicles.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('customer_vehicles.table')
            </div>
        </div>
    </div>
@endsection

resources/views/customer_vehicles/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Customer Vehicles
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('customer_vehicles.show_fields')
                    <a href="{!! route('customerVehicles.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/customer_vehicles/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $customerVehicles->id !!}</p>
</div>

<!-- Customer Id Field -->
<div class="form-group">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    <p>{!! $customerVehicles->customer_id !!}</p>
</div>

<!-- Vehicle Id Field -->
<div class="form-group">
    {!! Form::label('vehicle_id', 'Vehicle Id:') !!}
    <p>{!! $customerVehicles->vehicle_id !!}</p>
</div>

<!-- Detail Id Field -->
<div class="form-group">
    {!! Form::label('detail_id', 'Detail Id:') !!}
    <p>{!! $customerVehicles->detail_id !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $customerVehicles->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $customerVehicles->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $customerVehicles->deleted_at !!}</p>
</div>

resources/views/customer_vehicles/table.blade.php
<table class="table table-responsive" id="customerVehicles-table">
    <thead>
        <th>Customer Id</th>
        <th>Vehicle Id</th>
        <th>Detail Id</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($customerVehicles as $customerVehicles)
        <tr>
            <td>{!! $customerVehicles->customer_id !!}</td>
            <td>{!! $customerVehicles->vehicle_id !!}</td>
            <td>{!! $customerVehicles->detail_id !!}</td>
            <td>
                {!! Form::open(['route' => ['customerVehicles.destroy', $customerVehicles->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('customerVehicles.show', [$customerVehicles->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('customerVehicles.edit', [$customerVehicles->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>